command: ["streamlit", "run", "app.py", "--server.port", "8000"]
description: "Loan Underwriting Application powered by Agent Bricks"
env:
  - name: DATABRICKS_HOST
    value: "${workspace.host}"
  - name: DATABRICKS_TOKEN
    value: "${secrets.databricks_token}"
