apiVersion: v1
kind: Application
metadata:
  name: loan-underwriting-app
  description: "Loan Underwriting Application powered by Agent Bricks"
spec:
  command: ["streamlit", "run", "app.py", "--server.port", "8000"]
  env:
    - name: DATABRICKS_HOST
      value: "${workspace.host}"
    - name: DATABRICKS_TOKEN
      value: "${secrets.databricks_token}"
    - name: DATABRICKS_HTTP_PATH
      value: "${workspace.sql_warehouse_path}"
    - name: AGENT_BRICKS_ENDPOINT
      value: "${secrets.agent_bricks_endpoint}"
    - name: AGENT_BRICKS_API_KEY
      value: "${secrets.agent_bricks_api_key}"
  ports:
    - containerPort: 8000
      name: http
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
